version: '2.2'
services:
  front-builder:
    image: product.repo/frontend-builder:1.0.0
    environment:
      - APP_DIR=${APP_DIR}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker
      - ../../dist:/opt/frontend/dist
    command: sh -c 'build && publish'